spring:
  application:
    name: tolonbgeub
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
    #        use_sql_comments: true # SQL 내부에 /* */ 주석 추가
#        defer-datasource-initialization: true # script 파일이 hibernate 초기화 이후 동작하게 하기 위한 옵션
    hibernate:
      ddl-auto: create-drop # 실제 배포 환경에서는 다른 옵션을 사용해야 합니다.
    open-in-view: false

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
  expiry-seconds: ${JWT_EXPIRY_SECONDS}
  refresh-expiry-seconds: ${JWT_REFRESH_EXPIRY_SECONDS}
auth:
  scheme: "Bearer"
  header: Authorization
oauth:
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
    access_token_api: ${KAKAO_TOKEN_API}
    get_userinfo_api: ${KAKAO_USERINFO_API}

OPENVIDU_URL: ${OPENVIDU_URL}
OPENVIDU_SECRET: ${OPENVIDU_SECRET}